#!/usr/bin/env bash

fonts=(
    NotoNaskhArabic-Regular.ttf
    NotoSans-Regular.ttf
    NotoSansAdlam-Regular.ttf
    NotoSansBalinese-Regular.ttf
    NotoSansBamum-Regular.ttf
    NotoSansBassaVah-Regular.ttf
    NotoSansBatak-Regular.ttf
    NotoSansBengali-Regular.ttf
    NotoSansBuginese-Regular.ttf
    NotoSansBuhid-Regular.ttf
    NotoSansCanadianAboriginal-Regular.ttf
    NotoSansChakma-Regular.ttf
    NotoSansCham-Regular.ttf
    NotoSansCherokee-Regular.ttf
    NotoSansCoptic-Regular.ttf
    NotoSansDeseret-Regular.ttf
    NotoSansDevanagari-Regular.ttf
    NotoSansElbasan-Regular.ttf
    NotoSansEthiopic-Regular.ttf
    NotoSansGeorgian-Regular.ttf
    NotoSansGrantha-Regular.ttf
    NotoSansGujarati-Regular.ttf
    NotoSansGunjalaGondi-Regular.ttf
    NotoSansGurmukhi-Regular.ttf
    NotoSansHanifiRohingya-Regular.ttf
    NotoSansHanunoo-Regular.ttf
    NotoSansJavanese-Regular.ttf
    NotoSansKannada-Regular.ttf
    NotoSansKayahLi-Regular.ttf
    NotoSansKhmer-Regular.ttf
    NotoSansKhojki-Regular.ttf
    NotoSansKhudawadi-Regular.ttf
    NotoSansLao-Regular.ttf
    NotoSansLepcha-Regular.ttf
    NotoSansLimbu-Regular.ttf
    NotoSansLisu-Regular.ttf
    NotoSansMahajani-Regular.ttf
    NotoSansMalayalam-Regular.ttf
    NotoSansMandaic-Regular.ttf
    NotoSansMasaramGondi-Regular.ttf
    NotoSansMedefaidrin-Regular.ttf
    NotoSansMeeteiMayek-Regular.ttf
    NotoSansMendeKikakui-Regular.ttf
    NotoSansMiao-Regular.ttf
    NotoSansModi-Regular.ttf
    NotoSansMongolian-Regular.ttf
    NotoSansMro-Regular.ttf
    NotoSansMultani-Regular.ttf
    NotoSansNewa-Regular.ttf
    NotoSansNewTaiLue-Regular.ttf
    NotoSansNKo-Regular.ttf
    NotoSansOlChiki-Regular.ttf
    NotoSansOriya-Regular.ttf
    NotoSansOsage-Regular.ttf
    NotoSansOsmanya-Regular.ttf
    NotoSansPahawhHmong-Regular.ttf
    NotoSansPauCinHau-Regular.ttf
    NotoSansRejang-Regular.ttf
    NotoSansRunic-Regular.ttf
    NotoSansSamaritan-Regular.ttf
    NotoSansSaurashtra-Regular.ttf
    NotoSansSharada-Regular.ttf
    NotoSansShavian-Regular.ttf
    NotoSansSinhala-Regular.ttf
    NotoSansSoraSompeng-Regular.ttf
    NotoSansSoyombo-Regular.ttf
    NotoSansSundanese-Regular.ttf
    NotoSansSylotiNagri-Regular.ttf
    NotoSansSymbols-Regular.ttf
    NotoSansSymbols2-Regular.ttf
    NotoSansSyriac-Regular.ttf
    NotoSansTagalog-Regular.ttf
    NotoSansTagbanwa-Regular.ttf
    NotoSansTaiLe-Regular.ttf
    NotoSansTaiTham-Regular.ttf
    NotoSansTaiViet-Regular.ttf
    NotoSansTakri-Regular.ttf
    NotoSansTamil-Regular.ttf
    NotoSansTelugu-Regular.ttf
    NotoSansThaana-Regular.ttf
    NotoSansTifinagh-Regular.ttf
    NotoSansTifinaghAdrar-Regular.ttf
    NotoSansTifinaghAgrawImazighen-Regular.ttf
    NotoSansTifinaghAhaggar-Regular.ttf
    NotoSansTifinaghAir-Regular.ttf
    NotoSansTifinaghAPT-Regular.ttf
    NotoSansTifinaghAzawagh-Regular.ttf
    NotoSansTifinaghGhat-Regular.ttf
    NotoSansTifinaghHawad-Regular.ttf
    NotoSansTifinaghRhissaIxa-Regular.ttf
    NotoSansTifinaghSIL-Regular.ttf
    NotoSansTifinaghTawellemmet-Regular.ttf
    NotoSansTirhuta-Regular.ttf
    NotoSansVai-Regular.ttf
    NotoSansWancho-Regular.ttf
    NotoSansWarangCiti-Regular.ttf
    NotoSansYi-Regular.ttf
    NotoSansZanabazarSquare-Regular.ttf
    NotoSerif-Regular.ttf
    NotoSerifBalinese-Regular.ttf
    NotoSerifBengali-Regular.ttf
    NotoSerifDevanagari-Regular.ttf
    NotoSerifDogra-Regular.ttf
    NotoSerifEthiopic-Regular.ttf
    NotoSerifGeorgian-Regular.ttf
    NotoSerifGrantha-Regular.ttf
    NotoSerifGujarati-Regular.ttf
    NotoSerifGurmukhi-Regular.ttf
    NotoSerifKannada-Regular.ttf
    NotoSerifKhmer-Regular.ttf
    NotoSerifKhojki-Regular.ttf
    NotoSerifLao-Regular.ttf
    NotoSerifMalayalam-Regular.ttf
    NotoSerifMyanmar-Regular.ttf
    NotoSerifNPHmong-Regular.ttf
    NotoSerifSinhala-Regular.ttf
    NotoSerifTamil-Regular.ttf
    NotoSerifTelugu-Regular.ttf
    NotoSerifTibetan-Regular.ttf
    NotoSerifYezidi-Regular.ttf
    Pyidaungsu-2.5.3_Regular.ttf
    TwemojiMozilla.ttf
)

for font in "${fonts[@]}"; do
    echo "Copying $font..."
    sleep 0.01
done
