cat <<"EOF" > prefs.js
// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1762450569);
user_pref("app.update.lastUpdateTime.background-update-timer", 1762450569);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1762450569);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1762450569);
user_pref("basebrowser.migration.version", 6);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 155);
user_pref("browser.new_identity.confirm_newnym", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.preferences.experimental.hidden", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.search.totalSearches", 16);
user_pref("browser.security_level.noscript_inited", true);
user_pref("browser.security_level.security_custom", false);
user_pref("browser.security_level.security_slider", 1);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20251028094500");
user_pref("browser.startup.homepage_override.mstone", "140.4.0");
user_pref("browser.startup.homepage_override.torbrowser.version", "15.0");
user_pref("browser.startup.lastColdStartupCheck", 1762450543);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"vertical-spacer\",\"urlbar-container\",\"security-level-button\",\"new-identity-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"_73a6fe31-595d-460b-a920-fcc0f8843232_-browser-action\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"_73a6fe31-595d-460b-a920-fcc0f8843232_-browser-action\",\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"unified-extensions-area\",\"vertical-tabs\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":22,\"currentVersionBaseBrowser\":2,\"currentVersionTorBrowser\":1,\"newElementCount\":0}");
user_pref("browser.urlbar.placeholderName.private", "DuckDuckGo");
user_pref("captchadetection.lastSubmission", 1762009);
user_pref("devtools.everOpened", true);
user_pref("devtools.toolbox.footer.height", 341);
user_pref("devtools.toolbox.splitconsole.open", true);
user_pref("devtools.toolsidebar-height.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector", 700);
user_pref("devtools.toolsidebar-width.inspector.splitsidebar", 350);
user_pref("distribution.iniFile.exists.appversion", "140.4.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("dom.security.https_only_mode_ever_enabled_pbm", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.lastAppBuildId", "20251028094500");
user_pref("extensions.lastAppVersion", "140.4.0");
user_pref("extensions.lastPlatformVersion", "140.4.0");
user_pref("extensions.lastTorBrowserVersion", "15.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.torlauncher.prompt_at_startup", false);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{73a6fe31-595d-460b-a920-fcc0f8843232}", true);
user_pref("extensions.webextensions.uuids", "{\"{73a6fe31-595d-460b-a920-fcc0f8843232}\":\"b0c35d5a-26b4-4cba-a474-37f27617c2fb\",\"default-theme@mozilla.org\":\"ec8b033a-06f6-47be-ba69-7280bfeab622\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx-shader-check.build-version", "20251028094500");
user_pref("gfx-shader-check.device-id", "0x1c03");
user_pref("gfx-shader-check.driver-version", "32.0.15.7640");
user_pref("gfx-shader-check.ptr-size", 8);
user_pref("gfx.font_rendering.graphite.enabled", false);
user_pref("gfx.font_rendering.opentype_svg.enabled", false);
user_pref("idle.lastDailyNotification", 1762009978);
user_pref("intl.accept_languages", "en-US, en");
user_pref("intl.language_notification.shown", true);
user_pref("javascript.options.asmjs", false);
user_pref("javascript.options.baselinejit", false);
user_pref("javascript.options.ion", false);
user_pref("javascript.options.native_regexp", false);
user_pref("mathml.disabled", true);
user_pref("media.gmp-manager.buildID", "20251028094500");
user_pref("media.gmp-manager.lastCheck", 1762009758);
user_pref("media.gmp-manager.lastEmptyCheck", 1762009758);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("media.videocontrols.picture-in-picture.video-toggle.first-seen-secs", 1762023646);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1762009979);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.globalprivacycontrol.was_ever_enabled", true);
user_pref("privacy.history.custom", true);
user_pref("privacy.prioritizeonions.showNotification", false);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.resistFingerprinting.letterboxing.didForceSize", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.spoof_english", 2);
user_pref("sanity-test.device-id", "0x1c03");
user_pref("sanity-test.driver-version", "32.0.15.7640");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20251028094500");
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.old-sidebar.has-used", true);
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1762009978);
user_pref("svg.disabled", true);
user_pref("toolkit.profiles.storeID", "800e808c");
user_pref("toolkit.startup.last_success", 1762450533);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("torbrowser.about_torconnect.user_has_ever_clicked_connect", true);
user_pref("torbrowser.homepage.search.onionize", true);
user_pref("torbrowser.migration.version", 9);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
EOF